export const ROLE_PERMISSIONS = {
  guest: {
    canViewPublicItems: true,
    canSearchItems: true,
    canReportLostItem: false,
    canReportFoundItem: false,
    canMessageUsers: false,
  },
  user: {
    canViewPublicItems: true,
    canSearchItems: true,
    canReportLostItem: true,
    canReportFoundItem: true,
    canMessageUsers: true,
    canEditOwnItems: true,
    canDeleteOwnItems: true,
  },
  moderator: {
    canViewPublicItems: true,
    canSearchItems: true,
    canReportLostItem: true,
    canReportFoundItem: true,
    canMessageUsers: true,
    canEditOwnItems: true,
    canDeleteOwnItems: true,
    canModerateItems: true,
    canViewReports: true,
    canBanUsers: false,
  },
  admin: {
    canViewPublicItems: true,
    canSearchItems: true,
    canReportLostItem: true,
    canReportFoundItem: true,
    canMessageUsers: true,
    canEditOwnItems: true,
    canDeleteOwnItems: true,
    canModerateItems: true,
    canViewReports: true,
    canBanUsers: true,
    canManageModerators: true,
    canAccessAdminPanel: true,
  },
  super_admin: {
    canViewPublicItems: true,
    canSearchItems: true,
    canReportLostItem: true,
    canReportFoundItem: true,
    canMessageUsers: true,
    canEditOwnItems: true,
    canDeleteOwnItems: true,
    canModerateItems: true,
    canViewReports: true,
    canBanUsers: true,
    canManageModerators: true,
    canAccessAdminPanel: true,
    canManageAdmins: true,
    canAccessAllData: true,
    canModifySystemSettings: true,
  },
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
    EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
    SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
    LOCKED_OUT: 'AUTH_LOCKED_OUT',
    TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  },
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
    MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
    INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
    VALUE_TOO_LONG: 'VALIDATION_VALUE_TOO_LONG',
    VALUE_TOO_SHORT: 'VALIDATION_VALUE_TOO_SHORT',
  },
  DATABASE: {
    RECORD_NOT_FOUND: 'DATABASE_RECORD_NOT_FOUND',
    DUPLICATE_ENTRY: 'DATABASE_DUPLICATE_ENTRY',
    FOREIGN_KEY_VIOLATION: 'DATABASE_FOREIGN_KEY_VIOLATION',
    CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  },
  STORAGE: {
    FILE_TOO_LARGE: 'STORAGE_FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'STORAGE_INVALID_FILE_TYPE',
    UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  },
  RATE_LIMIT: {
    TOO_MANY_REQUESTS: 'RATE_LIMIT_TOO_MANY_REQUESTS',
  },
} as const;

export const REPUTATION_POINTS = {
  ITEM_REPORTED: 5,
  ITEM_FOUND: 20,
  ITEM_RETURNED: 50,
  HELPFUL_TIP: 10,
  SUCCESSFUL_VERIFICATION: 25,
} as const;
